camins:
  texte:
    dossier_articles_wiki: "../donadas/brut/wikipedia/A"
    fichier_wiki_texte: "../donadas/processat/wikipedia_texte.csv"
  etiquetas:
    fichier_wiki_etiquetas_aleatori: "../donadas/etiquetas/wikipedia_dialectes_aleatori.csv"
    fichier_wiki_etiquetas_automatic: "../donadas/etiquetas/wikipedia_dialectes_automatic.csv"
    fichier_wiki_etiquetas_entropia: "../donadas/etiquetas/wikipedia_dialectes_entropia.csv"
  tokenizaire:
    dossier_tokenizaire: "../models/tokenizaire"
  classificador:
    xgboost:
      dossier_model: "../models/classificador/xgboost"
      prediccions: "../donadas/prediccions/xgboost/wikipedia_prediccions.csv"
      seleccion_paginas: "../donadas/prediccions/xgboost/seleccion_paginas_entropia.txt"

parametres:
  longor_min: 50
  longor_max: "inf"

dialectes:
  - gascon
  - provençal
  - auvernhat
  - lengadocian
